### ISSUE TITLE
確認表示と完了表示のマークアップをいい感じにする

### ISSUE THREAD

**Issue by chanfuku** [chanfuku/fameal_nj#1]
- 特にデザインの指定はないのでそれなりにいい感じにする。
- 確認表示で利用規約に同意するチェックボックスを付ける。
- そのチェックボックスにチェックしないと送信ボタンがアクティブにならないようにする。

**Comment by chanfuku** [comment]
これ、同意するチェックボックス置くの入力画面でもいい？どうしても確認画面がいいなら頑張るけど、結構大変だからどうしてもって訳じゃなかった入力画面に起きたい。

**Comment by chanfuku** [comment]
チェックボックスは入力画面でいい？

**Comment by simdy-yusuke-tanaka** [comment]
いいよ！
