### ISSUE TITLE
申し込み完了メール本文の修正

### ISSUE THREAD

**Issue by simdy-yusuke-tanaka** [chanfuku/fameal_nj#16]
テキストおくります

**Comment by chanfuku** [comment]
お問い合わせメールもよろしく

**Comment by simdy-yusuke-tanaka** [comment]
件名:【FAMEAL】お申し込みありがとうございます。

本文:
〇〇 〇〇 様

この度は、FAMEALにお申し込みいただきありがとうございます。
仮申し込みを受け付け致しました。

担当者から一度お客様についてヒヤリングさせて
いただぎ、当日に備えたいとおもっております。
お電話にてご連絡させていただきますので
少々お待ちください。

それでは何卒よろしくお願い致します。

FAMEAL一同

※本メールの送信元アドレスは、配信専用です。
　ご返信いただいても対応ができませんので、
    ご了承ください。

※本メールは、FAMEALへ仮お申込みをして
    頂いた方に自動送信しています。
　お心当たりがない場合は、誠に恐れ入りますが    
    メールを破棄して頂きますようお願い致しま
    す。

**Comment by simdy-yusuke-tanaka** [comment]
件名:【FAMEAL】お申し込みありがとうございます。

本文:
〇〇 〇〇 様

この度は、FAMEALにお申し込みいただきありがとうございます。
仮申し込みを受け付け致しました。

予約日時:

一度お客様についてヒヤリングさせていただぎ、
当日に備えたいとおもっております。
担当からご連絡させていただきますので
少々お待ちください。

それでは何卒よろしくお願い致します。

FAMEAL一同

※本メールの送信元アドレスは、配信専用です。
　ご返信いただいても対応ができませんので、
ご了承ください。

※本メールは、FAMEALへ仮お申込みをして
頂いた方に自動送信しています。
　お心当たりがない場合は、誠に恐れ入りますが
メールを破棄して頂きますようお願い致しま
す。

**Comment by chanfuku** [comment]
@0630yusuke 
お問い合わせメールの本文はどうする？

**Comment by simdy-yusuke-tanaka** [comment]
おくる！
