### ISSUE TITLE
フッターを作る

### ISSUE THREAD

**Issue by chanfuku** [chanfuku/fameal_nj#3]
<img width="798" alt="2017-03-09 23 40 53" src="https://cloud.githubusercontent.com/assets/11294616/23754875/e30adae6-0521-11e7-928d-2818fe6f8d3a.png">
<img width="681" alt="2017-03-09 23 40 42" src="https://cloud.githubusercontent.com/assets/11294616/23754876/e30b4274-0521-11e7-8337-64c742a1fa5a.png">

**Comment by simdy-yusuke-tanaka** [comment]
お問い合わせのページ内リンクを、
申し込みと一緒にするのでいいとおもう。
