### ISSUE TITLE
PC_サービス理念のテキスト配置修正

### ISSUE THREAD

**Issue by simdy-yusuke-tanaka** [chanfuku/fameal_nj#33]
![pc_](https://cloud.githubusercontent.com/assets/26354515/24159107/9834cac0-0ea1-11e7-87e1-30ce306b11fa.png)

全体的に上部に寄っている感じがあるので、バランスよくしたい。
文字サイズ大きくしたり良い感じで修正求む

**Comment by chanfuku** [comment]
これもこれ以上はおれには手に負えないっす、すんません、クローズします。てか、前も言ったけど画像にしちゃえばいいんじゃないかと思うよ。
