### ISSUE TITLE
PC/SP_「高齢者の皆様に」の文言変更

### ISSUE THREAD

**Issue by simdy-yusuke-tanaka** [chanfuku/fameal_nj#37]
「高齢者の皆様に」→ 「中高年の皆様に」へ変更

**Comment by chanfuku** [comment]
![456979484x](https://cloud.githubusercontent.com/assets/11294616/24243929/34189228-1000-11e7-993d-a82f6fd1519a.jpg)

**Comment by chanfuku** [comment]
中高年に変更したからクローズ
