### ISSUE TITLE
sp/pc_FAMEALとはのテキスト配置

### ISSUE THREAD

**Issue by simdy-yusuke-tanaka** [chanfuku/fameal_nj#65]
wantedly用にかりんちゃんに作ってもらった画像と同じくらいの配置にしてほしい。
今はちょっと上すぎる印象。

**Comment by 0630yusuke** [comment]
![Uploading famealu3068u306f.jpg…]()

**Comment by simdy-yusuke-tanaka** [comment]
![famealu3068u306f](https://cloud.githubusercontent.com/assets/26354515/25013748/cb8f8dd6-20af-11e7-8b44-3fffb53aaecc.jpg)

**Comment by chanfuku** [comment]
これPC用の画像だよね？SPのも頂戴な
